[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dependencies]
modql = {version = "0.4.1",features = ["with-sea-query"]}
serde = "1.0.228"
sqlx = {version = "0.8.6",features = ["macros","postgres","runtime-tokio-rustls","chrono"]}
sea-query={version ="0.32.7",features = ["with-chrono"]}
sea-query-binder ={version = "0.7.0",features = ["sqlx-postgres","with-chrono"]}
o2o="0.5.4"
chrono={version = "0.4.42",features = ["serde"]}